In [2]:
# 필요한 모듈 설치
import pandas as pd
import numpy as np
import seaborn as sns
import folium
import json
from folium.plugins import MarkerCluster

In [5]:
store = pd.read_csv("C:/Users/kjh96/Github/공모전/data/정제 데이터/상가유해시설_주소_fin.csv",encoding="CP949")
store.head(3)

,Unnamed: 0,개방서비스명,소재지전체주소,도로명전체주소,사업장명,좌표정보(X),좌표정보(Y),지번주소,도로명주소,법정동
0,0,청소년게임제공업,서울특별시 동작구 대방동 336-5번지 지하1층,"서울특별시 동작구 상도로 84 (대방동,지하1층)",게임랜드,37.499522,126.929982,서울특별시 동작구 대방동 336-5,서울특별시 동작구 상도로 84,대방동
1,1,청소년게임제공업,서울특별시 동작구 상도동 188-4번지 1층,NaN,삼미컴퓨터게임장,37.502936,126.936279,서울특별시 동작구 상도동 188-4,서울특별시 동작구 상도로 152,상도동
2,2,청소년게임제공업,서울특별시 동작구 사당동 168-62번지 지하1층,"서울특별시 동작구 사당로23길 130 (사당동,지하1층)",우주오락실,37.488440,126.972715,서울특별시 동작구 사당동 1159-2,서울특별시 동작구 사당로17길 52,사당동

# 유해시설

In [6]:
# 지리정보 시각화
geo_df = store

# 지리정보 시각화 모듈 folium 사용
map = folium.Map(location = [geo_df["좌표정보(X)"].mean(), geo_df["좌표정보(Y)"].mean()], zoom_start=12)

for n in geo_df.index :
                # 팝업에 들어갈 텍스트 지정
                popup_name = geo_df.loc[n,'사업장명'] + '-' + geo_df.loc[n,'지번주소']

                
                # 표시 마커 설정
                folium.CircleMarker(
                location = [geo_df.loc[n,'좌표정보(X)'], geo_df.loc[n,'좌표정보(Y)']],
                radius=3,
                popup = popup_name,
                color = "red",
                fill = True,
                fill_color = "red"
                ).add_to(map)

map.save('index.html') # 버젼 문제로 한글깨짐 따라서 html 형식으로 추출 
map

# 국가시설

In [7]:
faclity = pd.read_csv("C:/Users/kjh96/Github/공모전/data/정제 데이터/국가시설_주소_fin.csv",encoding="CP949")
faclity.head(3)

,Unnamed: 0,일반시설일련번호,기준년도,시설종류,시설명,전체집행연장,전체집행면적,미집행연장,위치정보,좌표정보(X),좌표정보(Y),지번주소,도로명주소,법정동
0,1,1125345,2015,노외주차장,주차장,0,841,0,사당동 산32-62,37.484039,126.965114,서울특별시 동작구 사당동 산 32-83,서울특별시 동작구 솔밭로 83,사당동
1,2,1125346,2015,노외주차장,주차장,0,1012,0,대방동 395-1,37.500180,126.926280,서울특별시 동작구 대방동 395-1,서울특별시 동작구 상도로 49,대방동
2,3,1125347,2015,노외주차장,주차장,0,606,0,신대방동 351-14,37.498745,126.927468,서울특별시 동작구 신대방동 351-14,서울특별시 동작구 여의대방로24차길 44,신대방동

In [8]:
faclity_bed = faclity[faclity["시설종류"].str.contains("배수시설|열원시설|공공하수도중 간선하수관|고등학교")]
faclity_bed.head(3)

,Unnamed: 0,일반시설일련번호,기준년도,시설종류,시설명,전체집행연장,전체집행면적,미집행연장,위치정보,좌표정보(X),좌표정보(Y),지번주소,도로명주소,법정동
66,68,1127034,2015,배수시설,수도공급설비,2000,7038,0,상도동 산75-1일대,37.493217,126.938407,서울특별시 동작구 상도동 산 75-1,서울특별시 동작구 국사봉1길 235-11,상도동
67,69,1127035,2015,배수시설,수도공급설비,277,277,0,상도동274-19,37.496963,126.934691,서울특별시 동작구 상도동 274-19,서울특별시 동작구 성대로10길 16,상도동
68,70,1127036,2015,배수시설,수도공급설비,592,592,0,상도동274-19,37.496963,126.934691,서울특별시 동작구 상도동 274-19,서울특별시 동작구 성대로10길 16,상도동

# 유해시설 및 국가 시설 및 녹지

In [9]:
fa = faclity_bed[["시설명","좌표정보(X)","좌표정보(Y)","지번주소"]]
fa["종류"] = "시설"

C:\Users\kjh96\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
st = store[["사업장명","좌표정보(X)","좌표정보(Y)","지번주소"]]
st.rename(columns={"사업장명":"시설명"},inplace = True)
st["종류"] = "상가"

C:\Users\kjh96\anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\Users\kjh96\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
fa_st = pd.concat([fa,st])
fa_st = fa_st.reset_index(drop=True)

In [12]:
green = pd.read_csv("C:/Users/kjh96/Github/공모전/data/정제 데이터/자연녹지지역_주소.csv",encoding="CP949")
green = green[["용도지역명2","좌표정보(X)","좌표정보(Y)","지번주소"]]
green["종류"] = "녹지"
green.rename(columns = {"용도지역명2":"시설명"}, inplace = True)

In [13]:
df = pd.concat([fa_st,green])
df = df.reset_index(drop=True)

In [14]:
df.head(3)

      시설명    좌표정보(X)     좌표정보(Y)                  지번주소  종류
0  수도공급설비  37.493217  126.938407  서울특별시 동작구 상도동 산 75-1  시설
1  수도공급설비  37.496963  126.934691  서울특별시 동작구 상도동 274-19  시설
2  수도공급설비  37.496963  126.934691  서울특별시 동작구 상도동 274-19  시설

In [15]:
# 지리정보 시각화
geo_df = df

# 지리정보 시각화 모듈 folium 사용
map = folium.Map(location = [geo_df["좌표정보(X)"].mean(), geo_df["좌표정보(Y)"].mean()], zoom_start=12 )

for n in geo_df.index :
                # 팝업에 들어갈 텍스트 지정
                popup_name = geo_df.loc[n,'시설명'] + '-' + geo_df.loc[n,'지번주소']
                if geo_df.loc[n,'종류'] == '시설' :
                    icon_color = 'blue'
                elif geo_df.loc[n,'종류'] == '녹지' :
                    icon_color = 'green'
                else :
                    icon_color = 'red'
                    
                
                # 표시 마커 설정
                folium.CircleMarker(
                location = [geo_df.loc[n,'좌표정보(X)'], geo_df.loc[n,'좌표정보(Y)']],
                radius=50,
                radiusUnit="Meters",
                popup = popup_name,
                color = icon_color,
                fill = True ,
                weight = 0.001,
                fill_color = icon_color
                ).add_to(map)

map.save('index.html') # 버젼 문제로 한글깨짐 따라서 html 형식으로 추출 
map